# these will feed into litellm
# please specify api keys (if needed) with environment variables
evaluator:
  model_name: "gpt-4o-mini"
  api_base: "https://api.openai.com/v1"
target:
  # model_name: "ollama/llama3.1:8b-instruct-q8_0"
  # api_base: "http://localhost:11434"
  model_name: "gpt-4o-mini"
  api_base: "https://api.openai.com/v1"
similarity_config:
  type: "api"
  model_name: "text-embedding-ada-002"
  api_base: "https://api.openai.com/v1"

# this uses huggingface's transformers library
# similarity_config:
#   type: "huggingface"
#   model_name: "google-bert/bert-base-uncased"
#   device: "cuda"

# sadly however, ollama does not currently provide openai-like embedding apis;
# or I will have the huggingface/torch access mode removed just use apis instead

# max depth of the self-consistency tree
max_depth: 4

# number of operations to be applied to the input.
# if you provide more operations than this number, the evaluator will only consider the first n operations.
n_operations: 2

# constraint to generate root using evalutor model.
constraints: "Write a simple sentence about artificial intelligence in 20 words."

prompt_template: |
  Generate {n_operations} pairs of transform-reverse operations for testing language model consistency.
  Please make sure that these operations should be fit to perform on the root text: "{root}".
  Each operation should modify the text and its reverse should restore it.
  Format each line as: "transform operation | reverse operation"
  Example: "translate to French | translate back to English"
  "translate to Japanese | translate back to English"
  Also, it can be: "reverse each sentence to get the opposite meaning | reverse each sentence to get the opposite meaning"
  Or: "summarize the text in extremely short form | expand the summary to a normal text"
  Please try out what I have suggested above and then come up with your own ideas. Please avoid overly simple operations like "add a period | remove a period" or "capitalize the first letter | lowercase the first letter".
  Please start each line without '- ', '1. ', 'a. ', 'i. ', etc. Keep it simple and clear. Just the operation and its reverse.

# optional
# if you provide a root, it will override the root generated by the evaluator model.
root: "Artificial intelligence enhances the efficiency of various industries by automating tasks, analyzing data, and providing insights for better decision-making."

# optional
# if you provide a list of operations, it will override the operations generated by the evaluator model.
# operations:
#   - ["replace all nouns with synonyms", "replace all synonyms with the original nouns"]
#   - ["convert to passive voice", "convert back to active voice"]
#   - ["remove all adjectives", "restore the eliminated adjectives"]

# evaluation parameters
# "1" stands for L-1 AVG Similarity: the average similarity between direct parent-child node pairs
# "2" stands for L-2 AVG Similarity: the average similarity between grandparent-parent-child node triplets
# ...
distance: [1, 2, 3, 5]
